### ISSUE TITLE
Problem with build release

### ISSUE THREAD

**Issue by zentechthaingo** [Block-Equity/stellar-android-wallet#184]
//removing the default provider coming from Android SDK.
        Security.removeProvider("BC")
        Security.addProvider(BouncyCastleProvider() as Provider?)

I build release and have problems with that code if minify = true

**Comment by dabitdev** [comment]
hi @zentechthaingo  thank for you interest on our open source wallet.
I will look at this and provide support for `minify`.

**Comment by zentechthaingo** [comment]
I use some code of Block-Equity, in my project. it is keystore and genrate seed. When I build with minify = true, my app build success but it crash: with message error:
```
     Caused by: java.security.KeyStoreException: BKS not found
     java.net.SocketException: java.security.NoSuchAlgorithmException
then when I comment this code 
    Security.removeProvider("BC")
    Security.addProvider(BouncyCastleProvider() as Provider?)
```
it work again.
I think it due my 
```
signingConfigs {

        release {
            storeFile file(RELEASE_STORE_FILE)
            storePassword RELEASE_STORE_PASSWORD
            keyAlias RELEASE_KEY_ALIAS
            keyPassword RELEASE_KEY_PASSWORD
        }
    }
```
I want to ask you. What we need BouncyCastleProvider() and Security.removeProvider("BC").
Thank for you support. I love your open source wallet.

**Comment by dabitdev** [comment]
Hi @zentechthaingo, I got this following information from Soneso/stellar-java-mnemonic

If you add the library to a project running Java 1.7 or lower, then you need Bouncy Castle as well, because some of the security algorithms used within the library are supported starting with Java 1.8 only. After adding that dependency, add the following lines of code at your project entry point.

Security.removeProvider("BC");
Security.insertProviderAt(new BouncyCastleProvider(), 1);

In that way you are adding Bouncy Castle as the main provider for security algorithms.
